services:
  php:
    image: dunglas/frankenphp
    # todo Uncomment the following line if you want to use a custom Dockerfile
    build:
      context: .
      dockerfile: ./docker/Dockerfile-php
    # todo Uncomment the following line if you want to run this in a production environment
    # restart: always
    environment:
      CADDY_GLOBAL_OPTIONS: debug
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3

    volumes:
      - caddy_data:/data
      - caddy_config:/config
    # todo Comment the following line in production, it allows for more readable logs in development
    tty: true

  nodejs:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    # todo Uncomment the following line to use a pre-built Node.js 18 Alpine image instead of building from a Dockerfile
    # image: node:18-alpine

# Volumes needed for Caddy's certificates and configuration
volumes:
  caddy_data:
  caddy_config:
